language: node_js
node_js:
- 10.13.0

branches:
  only:
  - staging-firebase
  - production-firebase

before_script:
  - yarn

script:
  - yarn preserve

deploy:
  provider: script
  script: "./bin/travis_deploy.sh"
  skip_cleanup: true
  on:
    branch:
    - staging-firebase
    - production-firebase
notifications:
  email:
    on_failure: change
    on_success: change