language: node_js
node_js:
- 10.13.0

branches:
  only:
  - master

before_script:
- yarn

script:
- travis_wait 20 yarn deploy-app

notifications:
  email:
    on_failure: change
    on_success: change