language: node_js
node_js:
- 10.13.0

branches:
  only:
  - staging-firebase
  - production-firebase

before_script:
- yarn

script: "./bin/travis_deploy.sh"

notifications:
  email:
    on_failure: change
    on_success: change